name: Context demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use context variables
        run: |
          echo "This WF is triggered by ${{ github.actor }}"
          echo "The repo name is ${{ github.repository }}"
