name: Inputs demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        default: dev
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: "Deploying the app to ${{ inputs.environment }}"
