name: Outputs
on: push
jobs:
  build:
    outputs:
      version: ${{ steps.build1.outputs.version }}
    runs-on: ubuntu-slim
    steps:
      - name: Build
        id: build1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-slim
    steps:
      - name: Deploy
        run: echo "{{ needs.build.outputs.version }}"
