name: Outputs
on: push
jobs:
  build:
    outputs:
      version: ${{ steps.step1.outputs.veersion }}
    runs-on: ubuntu-slim
    steps:
      - name: Build
        id: build1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-slim
    steps:
      - name: Deploy the App
        run: echo "Deploying version: ${{ needs.build.outputs.version }}"
        
